"""
Overlord11 - Save Memory Tool
================================
Persist a key fact, insight, or context entry to a Markdown memory file.
Entries are structured with category and TTL metadata for easy scanning.

Usage:
    python save_memory_tool.py --key "api_base_url" --value "https://api.example.com/v1"
    python save_memory_tool.py --key "sprint_goal" --value "Ship auth module" --category decision --ttl 7d
    python save_memory_tool.py --key "db_host" --value "localhost" --category config --target_file project_memory.md
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Literal, Optional


VALID_CATEGORIES = ("context", "finding", "decision", "error", "config", "wip", "handoff")
VALID_TTLS = ("session", "24h", "7d", "30d", "persistent")

DEFAULT_TARGET = "Consciousness.md"


def save_memory(
    key: str,
    value: str,
    category: str = "context",
    ttl: str = "7d",
    target_file: str = DEFAULT_TARGET,
) -> dict:
    """
    Persist a structured memory entry to the target Markdown file.

    Args:
        key:         Short descriptive identifier for this entry
                     (e.g., 'api_endpoint_base_url', 'current_sprint_goal').
        value:       Content to store. Keep under 200 words for effective sharing.
        category:    One of: context, finding, decision, error, config, wip, handoff.
                     Defaults to 'context'.
        ttl:         Time-to-live: 'session', '24h', '7d', '30d', or 'persistent'.
                     Defaults to '7d'.
        target_file: Path to the memory file. Defaults to 'Consciousness.md'.
                     Relative paths are resolved from the project root (3 levels up
                     from this script).

    Returns:
        dict with keys: status, message, key, category, ttl, file
    """
    if category not in VALID_CATEGORIES:
        return {
            "status": "error",
            "error": f"Invalid category {category!r}. Must be one of: {', '.join(VALID_CATEGORIES)}",
        }

    if ttl not in VALID_TTLS:
        return {
            "status": "error",
            "error": f"Invalid ttl {ttl!r}. Must be one of: {', '.join(VALID_TTLS)}",
        }

    # Resolve target file path
    if os.path.isabs(target_file):
        file_path = Path(target_file)
    else:
        project_root = Path(__file__).resolve().parent.parent.parent
        file_path = project_root / target_file

    file_path.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build a structured Markdown entry
    entry_lines = [
        f"\n## {key}",
        f"- **Category:** {category}",
        f"- **TTL:** {ttl}",
        f"- **Written:** {timestamp}",
        f"\n{value}\n",
        "---",
    ]
    entry = "\n".join(entry_lines) + "\n"

    # If file is new, prepend a header
    if not file_path.exists():
        header = f"# Memory Store\n\n> Auto-generated by save_memory tool.\n"
        entry = header + entry

    try:
        with open(file_path, "a", encoding="utf-8") as f:
            f.write(entry)
    except IOError as exc:
        return {"status": "error", "error": f"Could not write to {file_path}: {exc}"}

    return {
        "status": "success",
        "message": f"Memory entry '{key}' saved.",
        "key": key,
        "category": category,
        "ttl": ttl,
        "file": str(file_path),
    }


def main():
    import argparse
    import io

    if sys.platform == "win32":
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description="Overlord11 Save Memory Tool")
    parser.add_argument("--key", required=True, help="Memory entry key")
    parser.add_argument("--value", required=True, help="Memory entry value/content")
    parser.add_argument("--category", default="context",
                        choices=list(VALID_CATEGORIES), help="Memory category")
    parser.add_argument("--ttl", default="7d",
                        choices=list(VALID_TTLS), help="Time-to-live")
    parser.add_argument("--target_file", default=DEFAULT_TARGET,
                        help=f"Target memory file (default: {DEFAULT_TARGET})")

    args = parser.parse_args()

    result = save_memory(
        key=args.key,
        value=args.value,
        category=args.category,
        ttl=args.ttl,
        target_file=args.target_file,
    )
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result["status"] == "success" else 1)


if __name__ == "__main__":
    main()
